### ISSUE TITLE
[CHORE]: Split `Channels` from the main lib bundle.

### ISSUE THREAD

**Issue by highfivedenis** [Dashlane/ts-event-bus#8]
@pyrho added a `ChunkedChannel` recently to the lib which is cool but made me think about the separation of concern in the lib.

As we may want to add more and more channel in the future, it may be ideal to split `Channels` from the core of the lib.

That way we could `import * 'from ts-event-bus'` for the core.
And `import * from 'ts-event-bus/ChunkedChannel` or `import * from 'ts-event-bus/Channels/ChunkedChannel` for channels

**Comment by pyrho** [comment]
We could use multiple [webpack entry points](https://webpack.js.org/concepts/entry-points/) to achieve that.
